// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkettySchool.Data;

namespace SkettySchool.Migrations
{
    [DbContext(typeof(SkettySchoolContext))]
    partial class SkettySchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SkettySchool.Models.ClassModel", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClassDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassDescription = "I.T Class One",
                            ClassName = "I.T"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassDescription = "History Class One",
                            ClassName = "History"
                        });
                });

            modelBuilder.Entity("SkettySchool.Models.PupilModel", b =>
                {
                    b.Property<int>("PupilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PupilId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            PupilId = 1,
                            DateOfBirth = new DateTime(2000, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Claire",
                            LastName = "Dearing",
                            SchoolYear = 7,
                            UserType = "Pupil"
                        },
                        new
                        {
                            PupilId = 2,
                            DateOfBirth = new DateTime(1999, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tim",
                            LastName = "Murphey",
                            SchoolYear = 8,
                            UserType = "Pupil"
                        },
                        new
                        {
                            PupilId = 3,
                            DateOfBirth = new DateTime(1999, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lex",
                            LastName = "Murphey",
                            SchoolYear = 9,
                            UserType = "Pupil"
                        });
                });

            modelBuilder.Entity("SkettySchool.Models.TeacherModel", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Alan",
                            LastName = "Grant",
                            UserType = "Teacher"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Ellie",
                            LastName = "Sattler",
                            UserType = "Teacher"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Ian",
                            LastName = "Malcom",
                            UserType = "Teacher"
                        },
                        new
                        {
                            TeacherId = 4,
                            FirstName = "Owen",
                            LastName = "Grady",
                            UserType = "Teacher"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
